name: caddy-reverse-proxy

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "8777:8777" # http
      - "8778:8778" # https
      #- "443:443"
      #- "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - caddy
volumes:
  caddy_data:
  caddy_config:
networks:
  caddy: